FROM alpine AS runtime
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY sls-doh sls-doh
RUN adduser -D dns
USER dns
EXPOSE 8053
ENV PORT=8053
CMD /usr/bin/sls-doh --env -e ":$PORT"