service: sls-doh

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  dns-query:
    handler: bin/dns-query
    events:
      - http:
          path: dns-query
          method: get