service: sls-doh

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-central-1
  memorySize: 128
  apiGateway:
    binaryMediaTypes:
      - 'application/dns-message'
      - 'application/dns-udpwireformat'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  dns-query:
    handler: bin/dns-query
    events:
      - http:
          path: dns-query
          method: get
      - http:
          path: dns-query
          method: post