name: Docker Static List CI (Non Strict)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image with static list
      run: docker build . --file server/Dockerfile --tag docker.pkg.github.com/c-mueller/serverless-doh/server:$(date +%s)
